server:
  port: 8082

spring:
  application:
    name: IntegrationApi
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

restClient:
  outboundThirdPartyUrl: http://localhost:3000/transaction
  inboundWebhookUrl: http://localhost:8082
  outboundClientUrl: http://localhost:3100/transaction


